force-app/main/default/_metadata/objects/ALP_Cell__c/ALP_Cell__c.object-meta.xml
<CustomObject>
    <label>ALP Cell</label>
    <nameField>
        <displayFormat>ACN-{YYYY}{MM}{DD}-{00000000}</displayFormat>
        <label>ALP Cell Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALP Cells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/_metadata/objects/ALP_Cell__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <label>Column</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/_metadata/objects/ALP_Cell__c/fields/Row__c.field-meta.xml
<CustomField>
    <fullName>Row__c</fullName>
    <label>Row</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/spiral_matrix/entities/suppliers/ALP_SMTX_NextCellUpSupplier.cls
public with sharing class ALP_SMTX_NextCellUpSupplier implements ALP_SMTX_NextCellSupplierIntf {
    public ALP_Cell__c getNextCell(ALP_SMTX_SpiralGridIntf grid) {
        ALP_Cell__c lastPopulatedCell = grid.getLastPopulatedCell();
        return grid.get(new ALP_Cell__c(
                Row__c = lastPopulatedCell.Row__c - 1,
                Column__c = lastPopulatedCell.Column__c
        ));
    }
}