force-app/main/default/_metadata/objects/ALP_Cell__c/ALP_Cell__c.object-meta.xml
<CustomObject>
    <label>ALP Cell</label>
    <nameField>
        <displayFormat>ACN-{YYYY}{MM}{DD}-{00000000}</displayFormat>
        <label>ALP Cell Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALP Cells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/_metadata/objects/ALP_Cell__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <label>Column</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/_metadata/objects/ALP_Cell__c/fields/Contains_Mine__c.field-meta.xml
<CustomField>
    <fullName>Contains_Mine__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contains Mine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/_metadata/objects/ALP_Cell__c/fields/Row__c.field-meta.xml
<CustomField>
    <fullName>Row__c</fullName>
    <label>Row</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/minesweeper/entities/ALP_MNSP_SquareCellListFactory.cls
public with sharing class ALP_MNSP_SquareCellListFactory {
    private static final String MINE_MARKER = '*';

    private ALP_MNSP_SquareCellListFactory() {
    }

    private static ALP_MNSP_SquareCellListFactory instance;
    public static ALP_MNSP_SquareCellListFactory getInstance() {
        if (instance == null) {
            instance = new ALP_MNSP_SquareCellListFactory();
        }
        return instance;
    }

    public ALP_MNSP_SquareCellList createFor(List<String> rowStringList) {
        ALP_MNSP_SquareCellList cellList = new ALP_MNSP_SquareCellList();
        for (Integer rowIndex = 0; rowIndex < rowStringList.size() - 1; rowIndex++) {
            cellList.add(this.createFor(rowIndex, rowStringList[rowIndex]));
        }
        return cellList;
    }

    private ALP_MNSP_SquareCellList createFor(Integer rowIndex, String rowString) {
        ALP_MNSP_SquareCellList cellList = new ALP_MNSP_SquareCellList();
        List<String> columnStringList = rowString.split('');
        for (Integer columnIndex = 0; columnIndex < columnStringList.size() - 1; columnIndex++) {
            cellList.add(new ALP_Cell__c(
                    Row__c = rowIndex,
                    Column__c = columnIndex,
                    Contains_Mine__c = columnStringList[columnIndex] == MINE_MARKER
            ));
        }
        return cellList;
    }

}